<?xml version="1.0" encoding="utf-8"?><Database Name="MqttMessenger" Class="MessengerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MONSTERMACHINE\SQLEXPRESS1;Initial Catalog=MqttMessenger;Integrated Security=True" SettingsObjectName="MQTTMessengerDevApp.Properties.Settings" SettingsPropertyName="MqttMessengerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gmail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="C2DMID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ToID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FromID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SendingPending" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>